"""
Phase H / S6 -- read the lockfile when the manifest does not pin.

The node side has done this since Phase C: package.json records a RANGE, so
querying OSV with it reports CVEs against a version the project does not
install. `_npm_locked_versions` reads package-lock.json and uses what is
actually there.

Python never got the same treatment, and the consequence is measurable. Given
`flask>=2.0` in requirements.txt and `flask==3.0.3` in requirements.lock, the
analyzer reported 4 vulnerabilities -- against 2.0, a version the lockfile says
is not installed.

After S7 an unpinned requirement resolves to "unknown" rather than to a made-up
number, which is honest but unhelpful when the answer is sitting in a lockfile
one directory up. This fills those in.

Scope: the lockfile fills UNKNOWNS only. It does not overrule an exact pin --
that would be a conflict between two manifests, which is a different problem
and not one to resolve silently.
"""

import tempfile
from pathlib import Path

import pytest

from backend.app.analysis.dependency_analyzer import (
    _python_locked_versions,
    analyze_dependencies,
)


REQUIREMENTS_LOCK = """\
# generated by pip-compile
flask==3.0.3
requests==2.32.3
flit-core==3.9.0
"""

UV_LOCK = """\
version = 1

[[package]]
name = "flask"
version = "3.0.3"

[[package]]
name = "requests"
version = "2.32.3"
"""

POETRY_LOCK = """\
[[package]]
name = "flask"
version = "3.0.3"
description = "A simple framework"

[[package]]
name = "requests"
version = "2.32.3"
description = "HTTP for Humans"
"""


def _write(files):
    tmp = tempfile.TemporaryDirectory()
    repo = Path(tmp.name)
    for name, body in files.items():
        (repo / name).write_text(body, encoding="utf-8")
    return tmp, repo


def _analyze(files):
    tmp, repo = _write(files)
    try:
        return {d["name"].lower(): d for d in analyze_dependencies(str(repo))}
    finally:
        tmp.cleanup()


# ----------------------------------------------------------
# The lockfile readers
# ----------------------------------------------------------

@pytest.mark.parametrize("filename, body", [
    ("requirements.lock", REQUIREMENTS_LOCK),
    ("uv.lock", UV_LOCK),
    ("poetry.lock", POETRY_LOCK),
])
def test_each_lockfile_format_is_read(filename, body):
    tmp, repo = _write({filename: body})
    try:
        locked = _python_locked_versions(str(repo))
    finally:
        tmp.cleanup()

    assert locked.get("flask") == "3.0.3"
    assert locked.get("requests") == "2.32.3"


def test_no_lockfile_yields_an_empty_map():
    tmp, repo = _write({"requirements.txt": "flask>=2.0\n"})
    try:
        assert _python_locked_versions(str(repo)) == {}
    finally:
        tmp.cleanup()


def test_lockfile_names_are_normalised():
    """PEP 503: flit_core, flit-core and Flit.Core are the same project."""
    tmp, repo = _write({"requirements.lock": "Flit_Core==3.9.0\n"})
    try:
        locked = _python_locked_versions(str(repo))
    finally:
        tmp.cleanup()

    assert locked.get("flit-core") == "3.9.0"


# ----------------------------------------------------------
# End to end
# ----------------------------------------------------------

def test_unpinned_requirement_is_resolved_from_the_lockfile():
    deps = _analyze({
        "requirements.txt": "flask>=2.0\n",
        "requirements.lock": REQUIREMENTS_LOCK,
    })

    assert deps["flask"]["version"] == "3.0.3"
    assert deps["flask"]["version_source"] == "lockfile"
    assert deps["flask"]["constraint"] == ">=2.0"


def test_bare_requirement_is_resolved_from_the_lockfile():
    deps = _analyze({
        "requirements.txt": "requests\n",
        "requirements.lock": REQUIREMENTS_LOCK,
    })

    assert deps["requests"]["version"] == "2.32.3"
    assert deps["requests"]["version_source"] == "lockfile"


def test_underscore_hyphen_mismatch_still_resolves():
    """requirements.txt says flit_core; the lockfile says flit-core."""
    deps = _analyze({
        "requirements.txt": "flit_core>=3\n",
        "requirements.lock": REQUIREMENTS_LOCK,
    })

    assert deps["flit_core"]["version"] == "3.9.0"


def test_an_exact_pin_is_not_overruled_by_the_lockfile():
    """Two manifests disagreeing is a different problem; do not resolve it silently."""
    deps = _analyze({
        "requirements.txt": "flask==2.9.9\n",
        "requirements.lock": REQUIREMENTS_LOCK,
    })

    assert deps["flask"]["version"] == "2.9.9"
    assert deps["flask"]["version_source"] == "pinned"


def test_a_dependency_absent_from_the_lockfile_stays_unknown():
    deps = _analyze({
        "requirements.txt": "flask>=2.0\nsomething-unlocked>=1\n",
        "requirements.lock": REQUIREMENTS_LOCK,
    })

    assert deps["something-unlocked"]["version"] == "unknown"
    assert deps["something-unlocked"]["version_source"] == "unpinned"
