# ==========================================================
# File: llm_refactor_engine.py
# Location: backend/app/analysis
#
# Purpose
# ----------------------------------------------------------
# This module generates AI-assisted refactoring suggestions
# based on the results of the repository analysis pipeline.
#
# It combines:
# • Static analysis metrics
# • Code smell detection
# • LLM-generated suggestions
#
# The engine produces:
# • explanations
# • suggested improvements
# • optionally improved code
# • a diff patch representing the changes
# ==========================================================

from typing import Dict, Any
from app.analysis.patch_generator import PatchGenerator


class LLMRefactorEngine:
    """
    Orchestrates AI-assisted code refactoring based on
    repository analysis results.
    """

    # ======================================================
    # Initialization
    # ======================================================

    def __init__(self):
        self.patch_generator = PatchGenerator()

    # ======================================================
    # Main Refactor Function
    # ======================================================

    def generate_refactor(
        self,
        code: str,
        analysis_result: Dict[str, Any],
        complexity: Dict[str, Any],
        smells: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Generate AI-assisted refactoring suggestions.

        Parameters
        ----------
        code : str
            Original source code.

        analysis_result : Dict
            Output from LLM code analysis pipeline.

        complexity : Dict
            Complexity metrics from ComplexityAnalyzer.

        smells : Dict
            Code smell analysis results.

        Returns
        -------
        Dict
            Refactor explanation, suggestions, improved code,
            and generated patch.
        """

        # --------------------------------------------------
        # Safely extract analysis information
        # --------------------------------------------------

        analysis = analysis_result.get("analysis", {})

        explanation = analysis.get("explanation", "")
        suggestions = analysis.get("suggestions", [])

        improved_code = code  # default: no change

        # --------------------------------------------------
        # Example heuristic refactor rule
        # --------------------------------------------------
        # NOTE:
        # This is a placeholder. Real refactoring should be
        # generated by the LLM based on analysis signals.
        # --------------------------------------------------

        if complexity.get("max_loop_depth", 0) >= 3:
            suggestions.append(
                "Consider reducing nested loops using sets, "
                "dictionary lookups, or vectorized operations."
            )

        if complexity.get("cyclomatic_complexity", 0) > 10:
            suggestions.append(
                "Function complexity is high. Consider breaking "
                "the function into smaller helper functions."
            )

        # --------------------------------------------------
        # Handle smell formats safely
        # --------------------------------------------------

        smell_list = []

        if isinstance(smells, dict):
            smell_list = smells.get("code_smells", [])
        elif isinstance(smells, list):
            smell_list = smells

        if smell_list:
            suggestions.append(
                "Code smells detected. Consider refactoring for better readability "
                "and maintainability."
            )

        # --------------------------------------------------
        # Generate patch only if code changed
        # --------------------------------------------------

        patch = None

        if improved_code != code:
            patch = self.patch_generator.generate_patch(code, improved_code)

        return {
            "explanation": explanation,
            "suggestions": suggestions,
            "improved_code": improved_code,
            "patch": patch
        }